version: "3.8"

services:
  # Backend Service
  node-backend:
    container_name: backend
    build:
      context: ./backend # Path to the backend directory
    ports:
      - "5001:5001" # Expose the backend app on port 5001
    environment:
      JWT_SECRET: your_jwt_secret # Secret for JWT token-based authentication
    restart: always # Always restart the service if it fails or stops

  # Frontend Service
  node-frontend:
    container_name: frontend
    build:
      context: ./frontend # Path to the frontend directory
    ports:
      - "3000:3000" # Expose the frontend app on port 3000
    restart: always # Always restart the service if it fails or stops
