services:
  # Backend Service
  node-backend:
    container_name: backend
    build:
      context: ./backend # Path to the backend directory
    ports:
      - "5000:5000" # Expose your backend app on port 5000
    environment:
      JWT_SECRET: your_jwt_secret # JWT Secret for your app
    restart: always

  node-frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always
