
services:
  # Backend Service
  node-backend:
    container_name: backend
    build:
      context: ./backend # Path to the backend directory
    ports:
      - "5001:5001" # Expose the backend app on port 5001
    restart: always # Always restart the service if it fails or stops

  # Frontend Service
  node-frontend:
    container_name: frontend
    build:
      context: ./frontend # Path to the frontend directory
    ports:
      - "4000:4000" # Expose the frontend app on port 4000
    restart: always # Always restart the service if it fails or stops

  docs:
    container_name: docs
    ports:
      - "8000:8000"
    image: squidfunk/mkdocs-material
    volumes:
      - ./docs:/docs
    stdin_open: true
    tty: true
    restart: always # Always restart the service if it fails or stops
