// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $execute from "./routes/execute.ts";
import * as $index from "./routes/index.tsx";
import * as $lessons_lesson_ from "./routes/lessons/[lesson].tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $CodeLanguageSelector from "./islands/CodeLanguageSelector.tsx";
import * as $CodePlayground from "./islands/CodePlayground.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/execute.ts": $execute,
    "./routes/index.tsx": $index,
    "./routes/lessons/[lesson].tsx": $lessons_lesson_,
    "./routes/login.tsx": $login,
    "./routes/logout.tsx": $logout,
    "./routes/signup.tsx": $signup,
  },
  islands: {
    "./islands/CodeLanguageSelector.tsx": $CodeLanguageSelector,
    "./islands/CodePlayground.tsx": $CodePlayground,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
