site_name: Learning Programming

site_url: https://LearningProgramming.de/

theme:
  language: en

  name: material

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # font:
  #   text: Merriweather Sans
  #   code: Red Hat Mono

  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate

  icon:
    logo: fontawesome/solid/w

  logo: assets/logo.png

  favicon: assets/favicon.ico

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  #   social:
  #     - icon: simple/youtube
  #       link: https://youtube.com/@james-willett
  #     - icon: simple/linkedin
  #       link: https://linkedin.com/in/willettjames
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: Copyright &copy; 2024 Diego Carrera & Anatolii
